import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={inter.className + " scroll-smooth"}>
        <Navbar />
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}

/**
 * Link Component === href= "hyperlink" target scroll window.scrolTo(0,0)
 *
 
 */
